src/resources/templates.ts

Fixing a small spelling for the word "I" 
Close #5
- Fix character case for the word "I" in the template file

Fix: spelling mistake

---

src/resources/tech_icons.ts

Fixed Django logo path and its variants
Closes #9

🐛  fix: django tech icons

---

src/generators/readme/sections/snake.ts

🐛 fix: snake image src

---

src/components/canvas/index.tsx
src/components/canvas/styles.ts
src/components/index.ts
src/components/welcome/index.tsx
src/components/welcome/styles.ts

I added some content to empty canvas, in this case, a welcome section!

✨  feat: add welcome section to empty canvas

---

src/components/canvas/index.tsx

I changed the canvas component to render only on client side
Ref: https://github.com/vercel/next.js/discussions/17443

🐛  fix: clear button in the canvas middle

---

src/components/sections/base/index.tsx
src/components/sections/base/styles.ts

I fixed the error that appear on console when some section was rendered on canvas
Error: received 'false' for a non-boolean attribute 'clear'

🐛  fix: console error

---

src/components/modals/styles.ts

🐛  fix: highlighted panel when modal is open

---

package.json
src/pages/_app.tsx
yarn.lock

✨  feat: add vercel analytics

---

src/resources/templates.ts

ref: https://www.sitepoint.com/github-profile-readme/
I added a new template based in the @itsZed0 article!
Closes #30

✨  feat: new template

---

src/utils/filterArrayByQueryMatch/index.ts

I improved the 'filterArrayByQueryMatch' function to use the 'includes' string method instead of a regex query match
Closes #36

⚡  chore: improve filter array by query match func

---

src/utils/objectToQueryParams/index.ts

Added encoding to the query params value
Closes #48

🐛  fix: encoding query params

---

src/contexts/canvas.tsx

🐛  fix: close right panel if its section was deleted

---

src/resources/tech_icons.ts

updated broken icon URLs for the nestjs and amazon web services

🐛fix: update broken icon links for nestjs and amazon web services

---

src/pages/_app.tsx

I added the ezoic-site-verification meta tag

✨  feat: add ezoic meta tag

---

public/ads.txt

✨  feat: add ads.txt

---

src/templates/privacy-policy/index.tsx

I updated privacy-policy page with ezoic section

⚡  chore: update privacy-policy with ezoic section

---

src/resources/templates.ts

🐛  fix: image link

---

public/assets/pacman.svg
src/app/config/sections/index.ts
src/app/config/sections/pacman.ts
src/features/index.tsx
src/features/pacman/default-config.ts
src/features/pacman/index.ts
src/features/pacman/panel/fields.ts
src/features/pacman/panel/index.tsx
src/features/pacman/panel/styles.ts
src/features/pacman/parser.ts
src/features/pacman/section/index.tsx
src/features/pacman/section/styles.ts
src/types/sections.ts

I've added the ability to add a new widget. It's a pacman game. The widget work very similar to snake game. The widget generates an SVG image where pacman chases ghosts and eats contributions.

Add pacman animation

---

src/components/panels/new-section/contents.ts
src/components/panels/panels.ts
src/components/panels/recommended-resources/index.tsx
src/components/panels/recommended-resources/items.ts
src/components/panels/recommended-resources/styles.ts
src/features/pacman/parser.ts
src/templates/canvas/index.tsx
src/templates/result/index.tsx
src/types/panels.ts

I added a panel with recommended resources.

✨ feat: add recommended resources panel

---

src/resources/tech_icons.ts

- Remove broken Simple Icons due to copyright issues. Example: https://github.com/simple-icons/simple-icons/pull/10019
- Remove Atom icon: https://github.com/simple-icons/simple-icons/pull/9305
- Fix AWS, D3, Nuxt, and RStudio logos.

🐛 fix: update and remove broken icons

---

src/components/canvas/index.tsx
src/components/canvas/styles.ts
src/components/group-fields/index.tsx
src/components/inputs/input/index.tsx
src/components/inputs/select/index.tsx
src/components/inputs/switch/index.tsx
src/components/panels/panels.ts
src/components/panels/user-settings/fields.ts
src/components/panels/user-settings/index.tsx
src/components/panels/user-settings/styles.ts
src/types/panels.ts

I added a panel to be able to edit the github username.
Closes #87

✨ feat: add user settings panel

---

.github/workflows/ci.yml

⚡  chore: update the CI node version

---

src/resources/templates.ts

⚡  chore: add new template

---

src/contexts/canvas.tsx

I changed the right panel when clearing the canvas

🐛  fix:  change the right panel when clearing canvas

---

src/templates/result/index.tsx

🐛  fix:  external links

---

src/components/canvas/actions.tsx
src/components/panels/panels.ts
src/components/panels/reorder-sections/index.tsx
src/components/panels/reorder-sections/item.tsx
src/components/ui/primitives/atoms/clickable.tsx
src/types/panels.ts

I added a new panel to reorder the sections in an easier way

✨ feat: add panel to reorder sections

---

src/components/panels/reorder-sections/item.tsx

🐛 fix: wrong conditional

---

src/pages/_app.tsx

⚡  chore: add impact verification

---

src/pages/_app.tsx

⚡  chore: remove impact verification

---

src/components/panels/recommended-resources/index.tsx
src/components/panels/recommended-resources/items.ts

⚡  chore: add new affiliate link

---

src/resources/tech_icons.ts

I have updated and added Jetbrains products and tried to match the icon colours to the logo with a colour picker tool.
Let me know if there are any issues! 😊
Add CLion, DataGrip, GoLand, ReSharper, Rider, TeamCity.
Update IntelliJ, PhpStorm, PyCharm, RubyMine, WebStorm.

feat: add and update Jetbrains products in techs

---

src/components/ui/primitives/atoms/panel.tsx

🐛  fix: input focus overflow
